### ISSUE TITLE
  Error: Transaction reverted: function selector was not recognized and there's no fallback function at Token.<unrecognized-selector> (contracts/Token.sol:12)

### ISSUE THREAD

**Issue by Tzikas** [NomicFoundation/hardhat-boilerplate#70]
Getting this error when trying to transfer from account to another.  I tried resetting metamask but still nothing.  The eth leaves one account but doesn't enter the other: 

`eth_getTransactionReceipt
eth_blockNumber
eth_getTransactionReceipt
eth_blockNumber
eth_getBlockByHash
eth_call
  Contract call:       Token#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

  Error: Transaction reverted: function selector was not recognized and there's no fallback function
      at Token.<unrecognized-selector> (contracts/Token.sol:12)
      at HardhatNode.runCall (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:616:20)
      at EthModule._callAction (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:354:9)
      at HardhatNetworkProvider._sendWithLogging (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at JsonRpcHandler._handleRequest (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at Server.JsonRpcHandler.handleHttp (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)

eth_call
  Contract call:       Token#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

  Error: Transaction reverted: function selector was not recognized and there's no fallback function
      at Token.<unrecognized-selector> (contracts/Token.sol:12)
      at HardhatNode.runCall (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:616:20)
      at EthModule._callAction (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:354:9)
      at HardhatNetworkProvider._sendWithLogging (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at JsonRpcHandler._handleRequest (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at Server.JsonRpcHandler.handleHttp (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)

eth_call
  Contract call:       Token#balanceOf
  From:                0xfee96e4fa418e99367b85a6d788ca59a691b04b3
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

eth_call
  Contract call:       Token#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

  Error: Transaction reverted: function selector was not recognized and there's no fallback function
      at Token.<unrecognized-selector> (contracts/Token.sol:12)
      at HardhatNode.runCall (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:616:20)
      at EthModule._callAction (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:354:9)
      at HardhatNetworkProvider._sendWithLogging (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at JsonRpcHandler._handleRequest (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at Server.JsonRpcHandler.handleHttp (/Users/niko/Documents/Code/KATERPILLAR/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)

eth_call
  Contract call:       Token#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3
`

**Comment by fvictorio** [comment]
Hi @Tzikas, this issue tracker is for boilerplate related issues. Unless this is something you get from a fresh clone and run of the repo, we can't help you with your problem.

As a minor hint, this:

```
Contract call: Token#
From: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
To: 0x5fbdb2315678afecb367f032d93f642f64180aa3

Error: Transaction reverted: function selector was not recognized and there's no fallback function
```

Suggests that you are using an EOA (a non-contract address) as if it was an instance of a contract. Perhaps there's some part of your code where you are accidentally mixing signers and contracts.
